"""empty message

Revision ID: a8246d4b5814
Revises: 4bcb142a709b
Create Date: 2019-04-30 11:44:55.390014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8246d4b5814'
down_revision = '4bcb142a709b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade_log', sa.Column('modify_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_upgrade_log_modify_time'), 'upgrade_log', ['modify_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrade_log_modify_time'), table_name='upgrade_log')
    op.drop_column('upgrade_log', 'modify_time')
    # ### end Alembic commands ###
