"""empty message

Revision ID: e42837613422
Revises: eb872992975d
Create Date: 2019-03-12 10:53:23.718236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42837613422'
down_revision = 'eb872992975d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('package_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'package_version')
    # ### end Alembic commands ###
