"""empty message

Revision ID: eb872992975d
Revises: fc043212d548
Create Date: 2019-03-11 17:36:10.260047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb872992975d'
down_revision = 'fc043212d548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=64), nullable=True),
    sa.Column('package_content', sa.String(length=512), nullable=True),
    sa.Column('package_path', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_create_time'), 'package', ['create_time'], unique=False)
    op.create_index(op.f('ix_package_package_name'), 'package', ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_package_name'), table_name='package')
    op.drop_index(op.f('ix_package_create_time'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
